name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # Released in April 2024
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore sincere.sln
      - name: Build
        run: dotnet build ./Sincere --no-restore sincere.sln
      - name: Pack
        run: dotnet pack ./Sincere --no-restore sincere.sln
      - name: Test
        run: dotnet test --verbosity normal sincere.sln
